# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0003_auto_20170209_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlevel',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='sponsorlevel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='sponsorlevel',
            name='description_eu',
        ),
        migrations.RemoveField(
            model_name='sponsorlevel',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='sponsorlevel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sponsorlevel',
            name='name_eu',
        ),
    ]
