# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20170208_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='_abstract_ca_rendered',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='_abstract_en_rendered',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='_abstract_eu_rendered',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='_additional_notes_ca_rendered',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='_additional_notes_en_rendered',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='_additional_notes_eu_rendered',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='abstract_ca',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='abstract_ca_markup_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='abstract_en',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='abstract_en_markup_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='abstract_eu',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='abstract_eu_markup_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='additional_notes_ca',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='additional_notes_ca_markup_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='additional_notes_en',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='additional_notes_en_markup_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='additional_notes_eu',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='additional_notes_eu_markup_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='description_eu',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='title_ca',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='title_eu',
        ),
        migrations.RemoveField(
            model_name='proposalkind',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='proposalkind',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='proposalkind',
            name='name_eu',
        ),
        migrations.RemoveField(
            model_name='proposalkind',
            name='slug_ca',
        ),
        migrations.RemoveField(
            model_name='proposalkind',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='proposalkind',
            name='slug_eu',
        ),
    ]
