# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_speaker_track'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='user',
        ),
        migrations.AddField(
            model_name='workshop',
            name='speaker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='speakers.Speaker'),
        ),
    ]
