# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import markupfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Tal como quieres que apareza en el programa de la conferencia.', max_length=100, verbose_name='Nombre')),
                ('content', markupfield.fields.MarkupField(blank=True, default='', help_text="Unas palabras sobre el workshop. Edita usando <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", rendered_field=True, verbose_name='Contenido del workshop')),
                ('content_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workshops', verbose_name='Imagen')),
                ('_content_rendered', models.TextField(editable=False)),
                ('track', models.IntegerField(default=3)),
                ('speaker', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'workshops',
                'verbose_name': 'workshop',
            },
        ),
    ]
