# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_speaker_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='url_blog',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='url_github',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='url_mail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='speaker',
            name='url_twitter',
            field=models.TextField(blank=True, default=''),
        ),
    ]
