# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_auto_20170208_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='_biography_ca_rendered',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='_biography_en_rendered',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='_biography_es_rendered',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='_biography_eu_rendered',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='_biography_gl_rendered',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_ca',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_ca_markup_type',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_en',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_en_markup_type',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_es',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_es_markup_type',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_eu',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_eu_markup_type',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_gl',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='biography_gl_markup_type',
        ),
    ]
