# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_auto_20170315_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'speaker', 'verbose_name_plural': 'speakers'},
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Unas palabras sobre el speaker. Edita usando <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", rendered_field=True, verbose_name='Biografía'),
        ),
    ]
