# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_auto_20170427_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='presentation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='annotation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='url_blog',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='url_github',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='url_mail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='url_twitter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
