# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0005_auto_20170507_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='presentation_schedule',
            field=models.CharField(blank=True, default='00:00 - 00:01', max_length=16),
        ),
    ]
