# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0007_speaker_presentation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='url_blog_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='speaker',
            name='url_github_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='speaker',
            name='url_mail_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='speaker',
            name='url_twitter_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
