# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0008_auto_20170517_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='is_workshop',
            field=models.BooleanField(default=False),
        ),
    ]
