# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0009_speaker_is_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='presentation_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='speaker',
            name='presentation_2_schedule',
            field=models.CharField(blank=True, default='00:00 - 00:01', max_length=16),
        ),
        migrations.AddField(
            model_name='speaker',
            name='presentation_2_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
