# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20170427_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title']},
        ),
    ]
